/**
 * File: frontend/src/components/ui/skeleton.tsx
 * Purpose: shadcn/ui primitive (generated by the shadcn CLI, kept as source).
 * Contents:
 *   - skeleton: Skeleton loading placeholder.
 */
import { cn } from "@/lib/utils"

function Skeleton({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      className={cn("animate-pulse rounded-md bg-primary/10", className)}
      {...props}
    />
  )
}

export { Skeleton }
