# Generated by Django 5.1.4 on 2026-10-05 13:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_clarity', models.PositiveSmallIntegerField(help_text='How clearly the instructor explained concepts.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_engagement', models.PositiveSmallIntegerField(help_text='How engaging the session was.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_pace', models.PositiveSmallIntegerField(help_text='Whether the pacing felt right.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The submitter: the student themselves or a linked parent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='classes.session')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating_clarity__gte', 1), ('rating_clarity__lte', 5)), name='feedback_rating_clarity_range'), models.CheckConstraint(condition=models.Q(('rating_engagement__gte', 1), ('rating_engagement__lte', 5)), name='feedback_rating_engagement_range'), models.CheckConstraint(condition=models.Q(('rating_pace__gte', 1), ('rating_pace__lte', 5)), name='feedback_rating_pace_range')],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
